# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

# Coverage configuration
# ----------------------
coverage:
  range: 50..90 # First number represents red, and second represents green
  round: down # up, down, or nearest
  precision: 2 # Number of decimal places, between 0 and 5

  status:
    project:
      default:
        target: 50% # coverage must be above 50% to succeed
        base: auto # compare coverage to base branch for PRs and parent commit for non-PRs
    patch:
      default:
        target: 50% # the diff coverage must be 50%

# Pull request comments:
# ----------------------
# Diff is the Coverage Diff of the pull request.
# Files are the files impacted by the pull request
comment:
  layout: diff, files # accepted in any order: reach, diff, flags, and/or files
  behavior: default
  require_changes: false # always post the updated coverage comment -- even if coverage hasn't changed
